// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test.Data;

#nullable disable

namespace test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250315080231_DetailedModelCreate")]
    partial class DetailedModelCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("test.Models.Assumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Kategory");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Level");

                    b.Property<string>("SubLevel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SubLevel");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Assumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
