// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test.Data;

#nullable disable

namespace test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322064615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("test.Models.Assumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Level1")
                        .HasAnnotation("Relational:JsonPropertyName", "level1");

                    b.Property<string>("Level2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Level2")
                        .HasAnnotation("Relational:JsonPropertyName", "level2");

                    b.Property<string>("Level3")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Level3")
                        .HasAnnotation("Relational:JsonPropertyName", "level3");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("Value")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.ToTable("Assumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
