// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using test.Data;

#nullable disable

namespace test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("test.Models.Assumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Level1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Level1")
                        .HasAnnotation("Relational:JsonPropertyName", "level1");

                    b.Property<string>("Level2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Level2")
                        .HasAnnotation("Relational:JsonPropertyName", "level2");

                    b.Property<string>("Level3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Level3")
                        .HasAnnotation("Relational:JsonPropertyName", "level3");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("Value")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.ToTable("Assumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
